apiVersion: v1
kind: ConfigMap
metadata:
    labels:
        app: '{{ template "fullname" . }}'
        chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
        heritage: '{{ .Release.Service }}'
        release: '{{ .Release.Name }}'
    name: '{{ template "name" . }}-app'
data:
    APP_DEBUG: '{{ .Values.app.debug }}'
    APP_ENV: '{{ .Values.app.env }}'
    APP_OPCACHE_STAT: '{{ .Values.app.opcache.stat }}'
    APP_URL_BASE: '{{ .Values.app.url.base }}'
